-- O painel de status do mês deixou de usar a view `vw_extintores_status_mes`.
-- Use o script unificado:
--   db/migrate-painel-status-rpc.sql
--
-- (Este arquivo permanece só como referência histórica.)
